### ISSUE TITLE
Channel name injection

### ISSUE THREAD

**Issue by dober2** [heleon19/node-red-contrib-zattoo#1]

**Comment by heleon19** [comment]
Hi Dober2
Yes there is, find example below:

[{"id":"d2516fd9.d795","type":"inject","z":"b5608cb8.c7231","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":95,"y":120,"wires":[["42a0d67e.bf2eb8"]]},{"id":"9870e604.0233a8","type":"zattoo","z":"b5608cb8.c7231","name":"","zconfig":"ba293d3a.277d8","request":"stream-urls","channel":"","x":500,"y":120,"wires":[["fad49fe3.c1b6b"],[]]},{"id":"fad49fe3.c1b6b","type":"debug","z":"b5608cb8.c7231","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":700,"y":120,"wires":[]},{"id":"42a0d67e.bf2eb8","type":"change","z":"b5608cb8.c7231","name":"","rules":[{"t":"set","p":"channel","pt":"msg","to":"srf1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":300,"y":120,"wires":[["9870e604.0233a8"]]},{"id":"ba293d3a.277d8","type":"zattoo-config","z":"","name":"","lang":"","domain":""}]
